# Generated by Django 4.2.6 on 2023-10-20 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'This name is already in use.'}, max_length=30, unique=True)),
                ('description', models.TextField(blank=True, max_length=120)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Quantity must be at least 0.'), django.core.validators.MaxValueValidator(limit_value=100, message='Quantity must not exceed 100.')])),
            ],
        ),
    ]
